version: '3'

services:
  flask_app:
    container_name: root
    restart: always
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=True
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app --reload

